plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  Exclude:
    - gemfiles/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20

Minitest/MultipleAssertions:
  Enabled: false
