AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Style/ClassVars:
  Enabled: false
Metrics/AbcSize:
  Max: 20
